import os, re
import glob
import pandas as pd

### Configuration
configfile: os.getcwd()+"/../config/config.yaml"

ENV_DIR = os.getcwd()+"/../envs"
SAMPLES_FILE = config["samples_file"]
RESULTS_DIR = config["results_dir"]

# list of phages
with open(SAMPLES_FILE) as f:
    READ_FILES = {}
    HOSTS_LIST = {}

    for line in f:
        if line.strip():
            sample, r1, host = line.rstrip("\n").split("\t")[:3]
            READ_FILES[sample] = r1
            HOSTS_LIST[sample] = host

PHAGES_LIST = list(READ_FILES.keys())

### Rules to include
# Function to recursively include all .smk files
def include_smk_files(directory):
    for root, _, files in os.walk(directory):
        files.sort()
        for file in files:
            if file.endswith('.smk'):
                include: os.path.join(root, file)

# Include all .smk files from the rules directory and subdirectories
include_smk_files('rules/')

### Global rules
# Assembly rules
rule assembly_all_phages:
    input: expand(rules.assembly_reads_flye.output.assembly, sample = PHAGES_LIST)

rule filtered_assembly_all_phages:
    input: expand(rules.multiqc_assembly.output, sample = PHAGES_LIST)

# One rule to rule them all
rule pipeline_new_phage:
    output: os.path.join(RESULTS_DIR, "{sample}", "done.touch")
    input: 
        assembly_report = rules.multiqc_assembly.output,
        pharokka_plot = rules.pharokka_plot.output,
        phold_plot = rules.phold_plot.output,
        genotate_plot = rules.genotate_phold_plot.output,
        defenseFinder_report = rules.antiDefenseFinder.output, 
        phageterm_report = rules.phageterm.output,
        vibrant_report = rules.vibrant.output,
        genomad_report = rules.genomad.output,
        checkv_report = rules.checkv.output
    shell: """touch {output}"""
    
rule pipeline_all_phages:
    input: expand(os.path.join(RESULTS_DIR, "{sample}", "done.touch"), sample = PHAGES_LIST)

# Rule for a whole host
rule pipeline_one_host:
    output: os.path.join(RESULTS_DIR, "analysis_per_host", "{genus}", "done.touch")
    input:
	    ani = rules.fast_ani.output.fastani,
	    pharokka = rules.lovis4u_pharokka.output
    shell: """touch {output}"""
